### ISSUE TITLE
GC: unsupported target

### ISSUE THREAD

**Issue by proyb6** [ysbaddaden/gc#10] opened 2019-01-27 07:01 UTC
Compile first test on macOS Mojave, not supported on macOS?

```
Ss-MacBook-Pro:immix s$ crystal run -Dgc_none main.cr 
Error in main.cr:1: while requiring "prelude"

{% if flag?(:gc_none) %}
^

in /usr/local/Cellar/crystal/0.27.0/src/prelude.cr:38: expanding macro

no_win require "concurrent"
^~~~~~

in /usr/local/Cellar/crystal/0.27.0/src/prelude.cr:38: expanding macro

no_win require "concurrent"
^

in macro 'no_win' /usr/local/Cellar/crystal/0.27.0/src/prelude.cr:10, line 2:

   1.   
>  2.     require "concurrent"
   3.   

while requiring "concurrent"
in /usr/local/Cellar/crystal/0.27.0/src/concurrent.cr:3: while requiring "crystal/scheduler"

require "crystal/scheduler"
^

in /usr/local/Cellar/crystal/0.27.0/src/crystal/scheduler.cr:3: while requiring "thread"

require "thread"
^

in /usr/local/Cellar/crystal/0.27.0/src/thread.cr:108: instantiating 'new()'

  self.current = new
                 ^~~

in /usr/local/Cellar/crystal/0.27.0/src/thread.cr:45: instantiating 'Fiber.class#new()'

    @main_fiber = Fiber.new
                        ^~~

in /usr/local/Cellar/crystal/0.27.0/src/fiber.cr:93: GC: unsupported target (only <arch>-linux-gnu is supported)

    @stack_bottom = GC.stack_bottom
                       ^~~~~~~~~~~~

```

**Comment by ysbaddaden** [comment] 2019-01-27 08:31
Duplicate of #9.

**Closed by ysbaddaden** 2019-01-27 08:31 UTC
